# Generated by Django 4.1.5 on 2023-04-23 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0002_myuser_groups_myuser_user_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='account_number',
            field=models.CharField(default='', max_length=10, unique=True),
        ),
    ]
