# Generated by Django 4.1.5 on 2023-04-26 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0006_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('Deposit', 'Deposit'), ('Withdrawal', 'Withdrawal'), ('Airtime', 'Airtime'), ('Stransfer', 'Stransfer'), ('Rtransfer', 'Rtransfer')], max_length=10),
        ),
    ]
