# Generated by Django 4.1.5 on 2023-05-08 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0008_transaction_validation_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='validation_status',
        ),
    ]
