# Generated by Django 4.1.5 on 2023-05-13 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0010_myuser_is_deposit_validated_depositvalidationrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='is_deposit_validated',
        ),
    ]
