# Generated by Django 4.1.5 on 2023-05-13 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0011_remove_myuser_is_deposit_validated'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DepositValidationRequest',
        ),
    ]
