# Generated by Django 4.1.5 on 2023-05-20 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0012_delete_depositvalidationrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='is_suspended',
            field=models.BooleanField(default=False),
        ),
    ]
