# Generated by Django 4.1.5 on 2023-05-20 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0014_loan'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Loan',
        ),
    ]
