# Generated by Django 4.1.5 on 2023-05-30 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0016_loan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('Deposit', 'Deposit'), ('Withdrawal', 'Withdrawal'), ('Airtime', 'Airtime'), ('Sent', 'Sent'), ('Received', 'Received'), ('Utility', 'Utility'), ('Loan', 'Loan')], max_length=10),
        ),
    ]
