# Generated by Django 4.1.5 on 2023-06-03 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0018_loan_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='transaction_pin',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
