# Generated by Django 4.1.5 on 2023-06-08 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0020_alter_loan_interest_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='status',
            field=models.CharField(default='pending', max_length=30),
        ),
    ]
