# Generated by Django 4.1.5 on 2023-06-08 22:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0021_alter_loan_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='transaction_pin',
            field=models.CharField(default=0, max_length=4, validators=[django.core.validators.RegexValidator('^\\d{4}$', 'Transaction PIN must be a 4-digit number.')]),
            preserve_default=False,
        ),
    ]
