# Generated by Django 4.1.5 on 2023-06-12 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0022_myuser_transaction_pin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=100)),
                ('Message', models.TextField(max_length=10000)),
                ('Created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
